# Generated by Django 4.0.3 on 2022-03-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_university_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.IntegerField(),
        ),
    ]
