# Generated by Django 4.0.3 on 2022-03-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.ImageField(upload_to='images')),
                ('original_language', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=300)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('poster_path', models.ImageField(upload_to='images')),
                ('release_date', models.DateField(auto_created=None)),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=2)),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
