# Generated by Django 4.0.1 on 2022-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('iProductId', models.AutoField(primary_key=True, serialize=False)),
                ('vTitle', models.CharField(max_length=200)),
            ],
        ),
    ]
