# Generated by Django 4.0.1 on 2022-01-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerce', '0003_remove_product_dprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dPrice',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
