# Generated by Django 4.0.3 on 2022-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratting',
            name='overview',
            field=models.CharField(max_length=10000),
        ),
    ]
