# Generated by Django 4.0.3 on 2022-03-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_ratting_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratting',
            name='backdrop_path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
