# Generated by Django 4.0.3 on 2022-03-04 04:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_ratting_backdrop_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rattin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('genre_ids', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('movie_id', models.IntegerField()),
                ('original_language', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=10000)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('poster_path', models.CharField(max_length=255)),
                ('release_date', models.DateField(auto_created=None)),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=2)),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ratting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
